---

trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage: TerraformValidation
  jobs:
  - job: TerraformValidationjob
    continueOnError: false
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
        artifactName: 'terraform-manifests-out'
        publishLocation: 'pipeline'
        
